title: Aditi Verma # your name (or website title) here
logo: "/images/2022-04-17-11-54-51-373 - Copy.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  ğŸ‘©â€ğŸ’» <i>Graduate Technical Intern @ Intel Corporation</i>
  <br>
  ğŸ“ <i>M.Tech from Indian Institute of Information Technology, Lucknow.</i>
  <br>
  ğŸŒ <i><a href="https://www.linkedin.com/in/aditi-verma-330/">LinkedIn</a> || <a href="https://github.com/himaniaditi330/">GitHub</a></i>
  <br>
  ğŸ“§ <i><a href="mailto:himaniaditi330@gmail.com">himaniaditi330@gmail.com</a></i>
  <br>
  ğŸ“ <i>+91-630-647-4570</i>
  <br>
  ğŸŒ <i>Prayagraj, India </i>
  <br>
  <br><br><br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
